# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DsmDictionary' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'FirebaseAnalytics'
pod 'FirebaseAuth'
pod 'FirebaseFirestore'
pod 'FirebaseStorage'
pod 'FirebaseCore'
pod 'Kingfisher', '~> 7.0'

  # Pods for DsmDictionary

end
